export const SUBMIT_GROUP_TASK_REQUEST = 'SUBMIT_GROUP_TASK_REQUEST';
export const SUBMIT_GROUP_TASK_SUCCESS = 'SUBMIT_GROUP_TASK_SUCCESS';
export const SUBMIT_GROUP_TASK_FAILURE = 'SUBMIT_GROUP_TASK_FAILURE';