export const SUBMIT_GROUP_TASK_REQUEST = 'SUBMIT_GROUP_TASK_REQUEST';
export const SUBMIT_GROUP_TASK_SUCCESS = 'SUBMIT_GROUP_TASK_SUCCESS';
export const SUBMIT_GROUP_TASK_FAILURE = 'SUBMIT_GROUP_TASK_FAILURE';

export const UPDATE_GROUP_TASK_REQUEST = 'UPDATE_GROUP_TASK_REQUEST';
export const UPDATE_GROUP_TASK_SUCCESS = 'UPDATE_GROUP_TASK_SUCCESS';
export const UPDATE_GROUP_TASK_FAILURE = 'UPDATE_GROUP_TASK_FAILURE';